AllCops:
  Exclude:
    - 'bin/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'spec/spec_helper.rb'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'Guardfile'
  NewCops: enable
Layout/LineLength:
  Max: 100
Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context', 'feature']
Metrics/MethodLength:
  Max: 15
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false